services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    hostname: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d postgres"]
      interval: 2s
      timeout: 20s
      retries: 10

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${HOST_PORT}:${HOST_PORT}
    depends_on:
      postgresql:
        condition: service_healthy
    links:
      - postgresql